# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import ecserver_pb2 as ecserver__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ecserver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExternalCallStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformAction = channel.unary_unary(
                '/ecserver.ExternalCall/PerformAction',
                request_serializer=ecserver__pb2.Request.SerializeToString,
                response_deserializer=ecserver__pb2.Response.FromString,
                _registered_method=True)
        self.FetchEvent = channel.unary_stream(
                '/ecserver.ExternalCall/FetchEvent',
                request_serializer=ecserver__pb2.FetchEventRequest.SerializeToString,
                response_deserializer=ecserver__pb2.Event.FromString,
                _registered_method=True)


class ExternalCallServicer:
    """Missing associated documentation comment in .proto file."""

    def PerformAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformAction': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformAction,
                    request_deserializer=ecserver__pb2.Request.FromString,
                    response_serializer=ecserver__pb2.Response.SerializeToString,
            ),
            'FetchEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchEvent,
                    request_deserializer=ecserver__pb2.FetchEventRequest.FromString,
                    response_serializer=ecserver__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecserver.ExternalCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecserver.ExternalCall', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExternalCall:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PerformAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecserver.ExternalCall/PerformAction',
            ecserver__pb2.Request.SerializeToString,
            ecserver__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ecserver.ExternalCall/FetchEvent',
            ecserver__pb2.FetchEventRequest.SerializeToString,
            ecserver__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
